require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe GittosController do

  # This should return the minimal set of attributes required to create a valid
  # Gitto. As you add validations to Gitto, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { {  } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # GittosController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all gittos as @gittos" do
      gitto = Gitto.create! valid_attributes
      get :index, {}, valid_session
      assigns(:gittos).should eq([gitto])
    end
  end

  describe "GET show" do
    it "assigns the requested gitto as @gitto" do
      gitto = Gitto.create! valid_attributes
      get :show, {:id => gitto.to_param}, valid_session
      assigns(:gitto).should eq(gitto)
    end
  end

  describe "GET new" do
    it "assigns a new gitto as @gitto" do
      get :new, {}, valid_session
      assigns(:gitto).should be_a_new(Gitto)
    end
  end

  describe "GET edit" do
    it "assigns the requested gitto as @gitto" do
      gitto = Gitto.create! valid_attributes
      get :edit, {:id => gitto.to_param}, valid_session
      assigns(:gitto).should eq(gitto)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Gitto" do
        expect {
          post :create, {:gitto => valid_attributes}, valid_session
        }.to change(Gitto, :count).by(1)
      end

      it "assigns a newly created gitto as @gitto" do
        post :create, {:gitto => valid_attributes}, valid_session
        assigns(:gitto).should be_a(Gitto)
        assigns(:gitto).should be_persisted
      end

      it "redirects to the created gitto" do
        post :create, {:gitto => valid_attributes}, valid_session
        response.should redirect_to(Gitto.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved gitto as @gitto" do
        # Trigger the behavior that occurs when invalid params are submitted
        Gitto.any_instance.stub(:save).and_return(false)
        post :create, {:gitto => {  }}, valid_session
        assigns(:gitto).should be_a_new(Gitto)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Gitto.any_instance.stub(:save).and_return(false)
        post :create, {:gitto => {  }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested gitto" do
        gitto = Gitto.create! valid_attributes
        # Assuming there are no other gittos in the database, this
        # specifies that the Gitto created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Gitto.any_instance.should_receive(:update_attributes).with({ "these" => "params" })
        put :update, {:id => gitto.to_param, :gitto => { "these" => "params" }}, valid_session
      end

      it "assigns the requested gitto as @gitto" do
        gitto = Gitto.create! valid_attributes
        put :update, {:id => gitto.to_param, :gitto => valid_attributes}, valid_session
        assigns(:gitto).should eq(gitto)
      end

      it "redirects to the gitto" do
        gitto = Gitto.create! valid_attributes
        put :update, {:id => gitto.to_param, :gitto => valid_attributes}, valid_session
        response.should redirect_to(gitto)
      end
    end

    describe "with invalid params" do
      it "assigns the gitto as @gitto" do
        gitto = Gitto.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Gitto.any_instance.stub(:save).and_return(false)
        put :update, {:id => gitto.to_param, :gitto => {  }}, valid_session
        assigns(:gitto).should eq(gitto)
      end

      it "re-renders the 'edit' template" do
        gitto = Gitto.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Gitto.any_instance.stub(:save).and_return(false)
        put :update, {:id => gitto.to_param, :gitto => {  }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested gitto" do
      gitto = Gitto.create! valid_attributes
      expect {
        delete :destroy, {:id => gitto.to_param}, valid_session
      }.to change(Gitto, :count).by(-1)
    end

    it "redirects to the gittos list" do
      gitto = Gitto.create! valid_attributes
      delete :destroy, {:id => gitto.to_param}, valid_session
      response.should redirect_to(gittos_url)
    end
  end

end
